// Generated by scripts/generate_api_payloads.mjs. Do not hand-edit.
export default {
  "schema_version": 1,
  "generated_at": "2026-08-29T08:07:47-06:00",
  "source_as_of": "2026-08-29",
  "freshness": {
    "inside_sales_source_updated_at": "2026-08-29T14:06:39.701Z",
    "collections_source_fetched_at": "2026-08-29T06:04:55.955799-06:00",
    "source_health": {
      "statuses": {
        "yellow": 10,
        "green": 19
      },
      "red": 0,
      "yellow": 10,
      "green": 19
    }
  },
  "summary": {
    "current_workshop_count": 8,
    "current_workshop_total_written": 2063900,
    "current_workshop_total_collected": 1647150,
    "current_workshop_collection_rate": 0.7980764571926935,
    "amount_into_collections": 5168633.43,
    "collections_out": 2595073.4299999997,
    "pending_outstanding": 347059.165888,
    "six_week_collected": 484175,
    "ten_week_collected": 748550,
    "normalized_event_count": 30
  },
  "collections": [
    {
      "speaker": "Tony",
      "amountIntoCollections": 1707013.43,
      "collectionsOut": 601788.4299999999,
      "pendingOutstanding": 110416.075329,
      "sixWeekCollected": 178325,
      "tenWeekCollected": 280075,
      "dplOrCollectionMetric": "YTD collections performance · fetched 2026-08-29T06:04:55.955799-06:00"
    },
    {
      "speaker": "Jazey",
      "amountIntoCollections": 1564450,
      "collectionsOut": 1034100,
      "pendingOutstanding": 82626.7458,
      "sixWeekCollected": 199500,
      "tenWeekCollected": 250500,
      "dplOrCollectionMetric": "YTD collections performance · fetched 2026-08-29T06:04:55.955799-06:00"
    },
    {
      "speaker": "Megan",
      "amountIntoCollections": 944820,
      "collectionsOut": 438835,
      "pendingOutstanding": 83016.834532,
      "sixWeekCollected": 33400,
      "tenWeekCollected": 65525,
      "dplOrCollectionMetric": "YTD collections performance · fetched 2026-08-29T06:04:55.955799-06:00"
    },
    {
      "speaker": "Nick",
      "amountIntoCollections": 844850,
      "collectionsOut": 499350,
      "pendingOutstanding": 64812.01022699999,
      "sixWeekCollected": 72950,
      "tenWeekCollected": 152450,
      "dplOrCollectionMetric": "YTD collections performance · fetched 2026-08-29T06:04:55.955799-06:00"
    },
    {
      "speaker": "Nate",
      "amountIntoCollections": 107500,
      "collectionsOut": 21000,
      "pendingOutstanding": 6187.5,
      "sixWeekCollected": null,
      "tenWeekCollected": null,
      "dplOrCollectionMetric": "YTD collections performance · fetched 2026-08-29T06:04:55.955799-06:00"
    }
  ],
  "events": [
    {
      "market": "Boise, ID",
      "team": "Team Nick · Speaker Nick",
      "event_date": "2026-08-23",
      "buying_units": 30,
      "sold_closed": 11,
      "showed": 30,
      "total_written": 203050,
      "total_collected": 186550,
      "abc_breakdown": "A: 4 buyers · 2 sold (50%) · B: 6 buyers · 4 sold (67%) · C: 20 buyers · 5 sold (25%)"
    },
    {
      "market": "Grand Rapids, MI",
      "team": "Team Tony · Speaker Tony",
      "event_date": "2026-08-23",
      "buying_units": 33,
      "sold_closed": 17,
      "showed": 33,
      "total_written": 354000,
      "total_collected": 326200,
      "abc_breakdown": "A: 2 buyers · 2 sold (100%) · B: 4 buyers · 3 sold (75%) · C: 27 buyers · 12 sold (52% as reported)"
    },
    {
      "market": "Chicago, IL",
      "team": "Team Tony · Speaker Tony",
      "event_date": "2026-08-16",
      "buying_units": 51,
      "sold_closed": 22,
      "showed": 51,
      "total_written": 269500,
      "total_collected": 134450,
      "abc_breakdown": "A: 6 buyers · 3 sold (50%) · B: 7 buyers · 3 sold (43%) · C: 34 buyers · 15 sold (44%)"
    },
    {
      "market": "Denver, CO",
      "team": "Team Drecksel · Speaker Drecksel",
      "event_date": "2026-08-16",
      "buying_units": 26,
      "sold_closed": 11,
      "showed": 26,
      "total_written": 200650,
      "total_collected": 156650,
      "abc_breakdown": "A: 3 buyers · 2 sold (67%) · B: 4 buyers · 2 sold (50%) · C: 19 buyers · 7 sold (37%)"
    },
    {
      "market": "Indianapolis, IN",
      "team": "Team Shaw · Speaker Shaw",
      "event_date": "2026-08-16",
      "buying_units": 43,
      "sold_closed": 18,
      "showed": 43,
      "total_written": 218500,
      "total_collected": 213000,
      "abc_breakdown": "A: 3 buyers · 1 sold (33%) · B: 6 buyers · 4 sold (67%) · C: 34 buyers · 13 sold (38%)"
    },
    {
      "market": "Hartford, CT",
      "team": "Team Tony · Speaker Tony",
      "event_date": "2026-08-02",
      "buying_units": 52,
      "sold_closed": 23,
      "showed": 52,
      "total_written": 377500,
      "total_collected": 356100,
      "abc_breakdown": "A: 8 buyers · 4 sold (50%) · B: 4 buyers · 1 sold (25%) · C: 37 buyers · 17 sold (46%)"
    },
    {
      "market": "Memphis, TN",
      "team": "Team Drecksel · Speaker Drecksel",
      "event_date": "2026-08-02",
      "buying_units": 77,
      "sold_closed": 24,
      "showed": 77,
      "total_written": 331000,
      "total_collected": 200500,
      "abc_breakdown": "A: 7 buyers · 4 sold (57%) · B: 8 buyers · 4 sold (50%) · C: 57 buyers · 16 sold (26% as reported)"
    },
    {
      "market": "Tulsa Oklahoma",
      "team": "Team Nick · Speaker Nick",
      "event_date": "2026-08-02",
      "buying_units": 16,
      "sold_closed": 7,
      "showed": 16,
      "total_written": 109700,
      "total_collected": 73700,
      "abc_breakdown": "A: 2 sold · B: 0 sold · C: 5 sold"
    }
  ],
  "inside_sales": {
    "source_updated_at": "2026-08-29T14:06:39.701Z",
    "categories": [
      {
        "source": "BB - PIF",
        "leads": 479,
        "revenue": 3222246,
        "dpl": 6727,
        "revenueShare": 0.5490937730465026
      },
      {
        "source": "UTL Upsell",
        "leads": 1144,
        "revenue": 1554000,
        "dpl": 1358,
        "revenueShare": 0.264812718617469
      },
      {
        "source": "Jumpstart",
        "leads": 375,
        "revenue": 366147,
        "dpl": 976,
        "revenueShare": 0.062394068522284706
      },
      {
        "source": "ANB",
        "leads": 2019,
        "revenue": 359767.22000000003,
        "dpl": 178,
        "revenueShare": 0.06130690836399555
      },
      {
        "source": "BB - Collections",
        "leads": 92,
        "revenue": 202282.98,
        "dpl": 2199,
        "revenueShare": 0.03447046709385014
      },
      {
        "source": "BB - Canceled",
        "leads": 13,
        "revenue": 99855,
        "dpl": 7681,
        "revenueShare": 0.01701600644629818
      },
      {
        "source": "Pender",
        "leads": 166,
        "revenue": 42000,
        "dpl": 253,
        "revenueShare": 0.007157100503174838
      },
      {
        "source": "RNA",
        "leads": 2,
        "revenue": 18000,
        "dpl": 9000,
        "revenueShare": 0.0030673287870749306
      },
      {
        "source": "Expo Collections",
        "leads": 1,
        "revenue": 4000,
        "dpl": 4000,
        "revenueShare": 0.0006816286193499846
      },
      {
        "source": "BB - Recontracted",
        "leads": 1,
        "revenue": 0,
        "dpl": 0,
        "revenueShare": 0
      },
      {
        "source": "Buyer",
        "leads": 1,
        "revenue": 0,
        "dpl": 0,
        "revenueShare": 0
      },
      {
        "source": "expo buyer",
        "leads": 10,
        "revenue": 0,
        "dpl": 0,
        "revenueShare": 0
      },
      {
        "source": "Low Buyer",
        "leads": 12,
        "revenue": 0,
        "dpl": 0,
        "revenueShare": 0
      }
    ],
    "representatives": [
      {
        "rep": "Tyler M",
        "leads": 205,
        "revenue": 914000,
        "dpl": 4459,
        "collected": null,
        "collectedDpl": null,
        "source": "Lindsey/Replit › TLWB Inside Sales DPL › groups · fetched 2026-08-29T14:06:39.701Z"
      },
      {
        "rep": "Travis R",
        "leads": 1,
        "revenue": 4000,
        "dpl": 4000,
        "collected": null,
        "collectedDpl": null,
        "source": "Lindsey/Replit › TLWB Inside Sales DPL › groups · fetched 2026-08-29T14:06:39.701Z"
      },
      {
        "rep": "Hyatt",
        "leads": 273,
        "revenue": 1073721,
        "dpl": 3933,
        "collected": null,
        "collectedDpl": null,
        "source": "Lindsey/Replit › TLWB Inside Sales DPL › groups · fetched 2026-08-29T14:06:39.701Z"
      },
      {
        "rep": "Cory",
        "leads": 406,
        "revenue": 1311299.98,
        "dpl": 3230,
        "collected": null,
        "collectedDpl": null,
        "source": "Lindsey/Replit › TLWB Inside Sales DPL › groups · fetched 2026-08-29T14:06:39.701Z"
      },
      {
        "rep": "Steven K",
        "leads": 286,
        "revenue": 818489,
        "dpl": 2862,
        "collected": null,
        "collectedDpl": null,
        "source": "Lindsey/Replit › TLWB Inside Sales DPL › groups · fetched 2026-08-29T14:06:39.701Z"
      },
      {
        "rep": "Nick Helf",
        "leads": 112,
        "revenue": 261500,
        "dpl": 2335,
        "collected": null,
        "collectedDpl": null,
        "source": "Lindsey/Replit › TLWB Inside Sales DPL › groups · fetched 2026-08-29T14:06:39.701Z"
      },
      {
        "rep": "CD Manager",
        "leads": 36,
        "revenue": 57000,
        "dpl": 1583,
        "collected": null,
        "collectedDpl": null,
        "source": "Lindsey/Replit › TLWB Inside Sales DPL › groups · fetched 2026-08-29T14:06:39.701Z"
      },
      {
        "rep": "Ryan I",
        "leads": 461,
        "revenue": 593200,
        "dpl": 1287,
        "collected": null,
        "collectedDpl": null,
        "source": "Lindsey/Replit › TLWB Inside Sales DPL › groups · fetched 2026-08-29T14:06:39.701Z"
      },
      {
        "rep": "Dagan",
        "leads": 1,
        "revenue": 1000,
        "dpl": 1000,
        "collected": null,
        "collectedDpl": null,
        "source": "Lindsey/Replit › TLWB Inside Sales DPL › groups · fetched 2026-08-29T14:06:39.701Z"
      },
      {
        "rep": "Derek Merrill",
        "leads": 63,
        "revenue": 62800,
        "dpl": 997,
        "collected": null,
        "collectedDpl": null,
        "source": "Lindsey/Replit › TLWB Inside Sales DPL › groups · fetched 2026-08-29T14:06:39.701Z"
      },
      {
        "rep": "Brett Dean",
        "leads": 67,
        "revenue": 64500,
        "dpl": 963,
        "collected": null,
        "collectedDpl": null,
        "source": "Lindsey/Replit › TLWB Inside Sales DPL › groups · fetched 2026-08-29T14:06:39.701Z"
      },
      {
        "rep": "Bryan S",
        "leads": 347,
        "revenue": 296700,
        "dpl": 855,
        "collected": null,
        "collectedDpl": null,
        "source": "Lindsey/Replit › TLWB Inside Sales DPL › groups · fetched 2026-08-29T14:06:39.701Z"
      },
      {
        "rep": "Carson M",
        "leads": 157,
        "revenue": 55000,
        "dpl": 350,
        "collected": null,
        "collectedDpl": null,
        "source": "Lindsey/Replit › TLWB Inside Sales DPL › groups · fetched 2026-08-29T14:06:39.701Z"
      },
      {
        "rep": "Greg A",
        "leads": 1107,
        "revenue": 269212.9,
        "dpl": 243,
        "collected": null,
        "collectedDpl": null,
        "source": "Lindsey/Replit › TLWB Inside Sales DPL › groups · fetched 2026-08-29T14:06:39.701Z"
      },
      {
        "rep": "Larry L",
        "leads": 789,
        "revenue": 85875.32,
        "dpl": 109,
        "collected": null,
        "collectedDpl": null,
        "source": "Lindsey/Replit › TLWB Inside Sales DPL › groups · fetched 2026-08-29T14:06:39.701Z"
      },
      {
        "rep": "Chris Hall",
        "leads": 4,
        "revenue": 0,
        "dpl": 0,
        "collected": null,
        "collectedDpl": null,
        "source": "Lindsey/Replit › TLWB Inside Sales DPL › groups · fetched 2026-08-29T14:06:39.701Z"
      }
    ]
  }
} as const;
