// Generated by scripts/generate_api_payloads.mjs. Do not hand-edit.
export default {
  "schema_version": 1,
  "timezone": "America/Denver",
  "refresh_schedule": "5 8-22 * * *",
  "refresh_schedule_label": "Hourly at :05 from 8:05 AM through 10:05 PM Mountain",
  "queue_poll_seconds": 300,
  "last_checked": "2026-08-29T08:07:47-06:00",
  "last_published": "2026-08-29T08:07:47-06:00",
  "data_through": "2026-08-29",
  "schedule_through": "2026-09-11",
  "source_health": {
    "statuses": {
      "yellow": 10,
      "green": 19
    },
    "red": 0,
    "yellow": 10,
    "green": 19
  }
} as const;
