import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import ts from "typescript";

const root = path.resolve(import.meta.dirname, "..");
const readJson = (relative) => JSON.parse(fs.readFileSync(path.join(root, relative), "utf8"));
const evaluateTypeScriptExports = (relative) => {
  const source = fs.readFileSync(path.join(root, relative), "utf8");
  const output = ts.transpileModule(source, {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 },
    fileName: relative,
  }).outputText;
  const exported = {};
  const sandbox = { exports: exported, module: { exports: exported }, console };
  vm.runInNewContext(output, sandbox, { filename: relative, timeout: 10_000 });
  return sandbox.module.exports;
};
const writeGenerated = (relative, value) => {
  const destination = path.join(root, relative);
  fs.mkdirSync(path.dirname(destination), { recursive: true });
  fs.writeFileSync(destination, `// Generated by scripts/generate_api_payloads.mjs. Do not hand-edit.\nexport default ${JSON.stringify(value, null, 2)} as const;\n`);
};
const sum = (rows, key) => rows.reduce((total, row) => total + (Number(row[key]) || 0), 0);

const sourceHealth = readJson("data/source_health.json");
const phase2a = readJson("data/phase2a_audit.json");
const adapters = evaluateTypeScriptExports("src/data/tlwbPageAdapters.ts");
const visibleRows = sourceHealth.rows.filter((row) => !String(row.schedule_state).includes("coverage_requirement"));
const statuses = visibleRows.reduce((counts, row) => ({ ...counts, [row.status]: (counts[row.status] || 0) + 1 }), {});
const latestDataDates = visibleRows
  .filter((row) => row.schedule_state !== "upcoming")
  .map((row) => row.latest_data_date)
  .filter(Boolean)
  .sort();
const scheduleDates = visibleRows
  .filter((row) => row.page === "Schedule")
  .map((row) => row.latest_data_date)
  .filter(Boolean)
  .sort();

const statusPayload = {
  schema_version: 1,
  timezone: "America/Denver",
  refresh_schedule: "5 8-22 * * *",
  refresh_schedule_label: "Hourly at :05 from 8:05 AM through 10:05 PM Mountain",
  queue_poll_seconds: 300,
  last_checked: sourceHealth.generated_at,
  last_published: sourceHealth.build_timestamp,
  data_through: latestDataDates.at(-1) ?? null,
  schedule_through: scheduleDates.at(-1) ?? null,
  source_health: { statuses, red: statuses.red || 0, yellow: statuses.yellow || 0, green: statuses.green || 0 },
};

const collections = Array.from(adapters.speakerCollectionRows ?? []);
const events = Array.from(adapters.currentMiddleEndWorkshops ?? []).map((row) => ({
  market: row.market,
  team: row.team,
  event_date: row.eventDate,
  buying_units: row.buyingUnits,
  sold_closed: row.soldClosed,
  showed: row.showed,
  total_written: row.totalWritten,
  total_collected: row.totalCollected,
  abc_breakdown: row.abcBreakdown,
}));
const insideSales = {
  source_updated_at: adapters.insideSalesSourceUpdatedAt,
  categories: Array.from(adapters.insideSalesSourceCategories ?? []),
  representatives: Array.from(adapters.insideSalesRepRows ?? []),
};
const accountingPayload = {
  schema_version: 1,
  generated_at: sourceHealth.generated_at,
  source_as_of: latestDataDates.at(-1) ?? null,
  freshness: {
    inside_sales_source_updated_at: adapters.insideSalesSourceUpdatedAt,
    collections_source_fetched_at: adapters.collectionsSourceFetchedAt,
    source_health: statusPayload.source_health,
  },
  summary: {
    current_workshop_count: events.length,
    current_workshop_total_written: sum(events, "total_written"),
    current_workshop_total_collected: sum(events, "total_collected"),
    current_workshop_collection_rate: sum(events, "total_written") ? sum(events, "total_collected") / sum(events, "total_written") : null,
    amount_into_collections: sum(collections, "amountIntoCollections"),
    collections_out: sum(collections, "collectionsOut"),
    pending_outstanding: sum(collections, "pendingOutstanding"),
    six_week_collected: sum(collections, "sixWeekCollected"),
    ten_week_collected: sum(collections, "tenWeekCollected"),
    normalized_event_count: phase2a.counts?.event_roster ?? null,
  },
  collections,
  events,
  inside_sales: insideSales,
};

writeGenerated("api/_data/status.generated.ts", statusPayload);
writeGenerated("api/_data/accounting.generated.ts", accountingPayload);
console.log(`Generated protected API payloads: ${collections.length} collection rows, ${events.length} current workshop rows.`);